# Increase Gradle heap size
org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8 -XX:+HeapDumpOnOutOfMemoryError -XX:+UseParallelGC

# AndroidX & Jetifier
android.useAndroidX=true
android.enableJetifier=true

# Enable R8 for code shrinking
#android.enableR8=true

# Performance tweaks
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureondemand=true

# Network timeouts (for slow internet)
systemProp.http.socketTimeout=60000
systemProp.http.connectionTimeout=60000
